export default {
  drugs: [
    { name: "Ciprofar 500", type: "number", value: 0 },
    { name: "Ciprofloxacin 500", type: "number", value: 0 },
    { name: "Ciprocin 500", type: "number", value: 0 },
    { name: "ciprdiazole", type: "number", value: 0 },
    { name: "tavanic 500", type: "number", value: 0 },
    { name: "unictam 375", type: "number", value: 0 },
    { name: "tarivid 200", type: "number", value: 0 },
    { name: "septrin d.S", type: "number", value: 0 },
    { name: "suprax 200 tab", type: "number", value: 0 },
    { name: "suprax 400 tab", type: "number", value: 0 },
    { name: "augmentin 1g", type: "number", value: 0 },
    { name: "hibiotic 1g", type: "number", value: 0 },
    { name: "augmentin 625 tab", type: "number", value: 0 },
    { name: "augmentin 600 syrup", type: "number", value: 0 },
    { name: "hibiotic 600 syrup", type: "number", value: 0 },
    { name: "clavimox 625", type: "number", value: 0 },
    { name: "averozolid tab", type: "number", value: 0 },
    { name: "linezolid tab", type: "number", value: 0 },
    { name: "linizox tab", type: "number", value: 0 },
    { name: "gynoconazol 80 supp", type: "number", value: 0 },
    { name: "viatrazo 80 supp", type: "number", value: 0 },
    { name: "abimol supp", type: "number", value: 0 },
    { name: "voltaren supp", type: "number", value: 0 },
    { name: "pyral supp", type: "number", value: 0 },
    { name: "dolphin 12.5 supp", type: "number", value: 0 },
    { name: "proximol sachets", type: "number", value: 0 },
    { name: "epimag sachets", type: "number", value: 0 },
    { name: "urivin sachets", type: "number", value: 0 },
    { name: "urosolvine sachets", type: "number", value: 0 },
    { name: "ur-Aid sachets", type: "number", value: 0 },
    { name: "septrin syrup", type: "number", value: 0 },
    { name: "septazole syrup", type: "number", value: 0 },
    { name: "suprax 30ml", type: "number", value: 0 },
    { name: "suprax 60ml", type: "number", value: 0 },
    { name: "cefixime 30ml", type: "number", value: 0 },
    { name: "cefixime 60ml", type: "number", value: 0 },
    { name: "ultracaine gel", type: "number", value: 0 },
    { name: "extra cream", type: "number", value: 0 },
    { name: "faktu cream", type: "number", value: 0 },
    { name: "cataflam amp", type: "number", value: 0 },
    { name: "voltaren amp", type: "number", value: 0 },
    { name: "anticox amp", type: "number", value: 0 },
    { name: "spasmofen amp", type: "number", value: 0 },
    { name: "danset 4 amp", type: "number", value: 0 },
    { name: "danset 8 amp", type: "number", value: 0 },
    { name: "zofran 4 amp", type: "number", value: 0 },
    { name: "zofran 8 amp", type: "number", value: 0 },
    { name: "biovit-12 amp", type: "number", value: 0 },
    { name: "depovit amp", type: "number", value: 0 },
    { name: "androstat 80", type: "number", value: 0 },
    { name: "feburic 80", type: "number", value: 0 },
    { name: "unsiatem 80", type: "number", value: 0 },
    { name: "ambezim", type: "number", value: 0 },
    { name: "Corvizim tab", type: "number", value: 0 },
    { name: "alphintern", type: "number", value: 0 },
    { name: "Bristaflam tab", type: "number", value: 0 },
    { name: "lornoxicam tab", type: "number", value: 0 },
    { name: "Bendax tab ", type: "number", value: 0 },
    { name: "alzental tab ", type: "number", value: 0 },
    { name: "fluver tab", type: "number", value: 0 },
    { name: "milga advance", type: "number", value: 0 },
    { name: "milga", type: "number", value: 0 },
    { name: "betadine solution", type: "number", value: 0 },
    { name: "safetrium", type: "number", value: 0 },
    { name: "pepon plus", type: "number", value: 0 },
    { name: "bladogra 25", type: "number", value: 0 },
    { name: "bladogra 50", type: "number", value: 0 },
    { name: "minalax", type: "number", value: 0 },
    { name: "colchicine", type: "number", value: 0 },
    { name: "garamycin 40", type: "number", value: 0 },
    { name: "garamycin 80", type: "number", value: 0 },
    { name: "sofenacin 5", type: "number", value: 0 },
    { name: "sofenacin 10", type: "number", value: 0 },
    { name: "wintriaxone 1g", type: "number", value: 0 },
    { name: "xoraxon 1g", type: "number", value: 0 },
    { name: "fortum 1g", type: "number", value: 0 },
    { name: "unictam 1.5 gm vial", type: "number", value: 0 },
    { name: "wincef 1gm vial", type: "number", value: 0 },
    { name: "amikacin 500 vial amp", type: "number", value: 0 }, 
    { name: "vinosin cream", type: "number", value: 0 },
    { name: "marcal tab", type: "number", value: 0 },
    { name: "ferroduonal cap", type: "number", value: 0 },
    { name: "tadalong 5", type: "number", value: 0 },
    { name: "starkoprex 5", type: "number", value: 0 },
    { name: "starkoprex 20", type: "number", value: 0 },
    { name: "bone one 0.25", type: "number", value: 0 },
    { name: "bone care .25 tab", type: "number", value: 0 },
    { name: "one alpha .25 tab", type: "number", value: 0 },
    { name: "methoquick tab", type: "number", value: 0 },
    { name: "dimra tab", type: "number", value: 0 },
    { name: "controloc 20", type: "number", value: 0 },
    { name: "controloc 40", type: "number", value: 0 },
    { name: "bepra tab", type: "number", value: 0 },
    { name: "eucarbon tab", type: "number", value: 0 },
    { name: "new carbon", type: "number", value: 0 },
    { name: "healsec 20", type: "number", value: 0 },
    { name: "healsec 40", type: "number", value: 0 },
    { name: "omegapress 0.1", type: "number", value: 0 },
    { name: "omegapress 0.2", type: "number", value: 0 },
    { name: "tamsulin cap", type: "number", value: 0 },
    { name: "clovatil", type: "number", value: 0 },
    { name: "block alpha cap", type: "number", value: 0 },
    { name: "tamsulin plus", type: "number", value: 0 },
    { name: "uvamin retard cap", type: "number", value: 0 },
    { name: "macrofuran 50", type: "number", value: 0 },
    { name: "macrofuran 100", type: "number", value: 0 },
    { name: "mepafuran 50", type: "number", value: 0 },
    { name: "mepafuran 100", type: "number", value: 0 },
    { name: "incont tab", type: "number", value: 0 },
    { name: "imipramine tab", type: "number", value: 0 },
    { name: "itrapex 4 cap", type: "number", value: 0 },
    { name: "treflucan 150mg", type: "number", value: 0 },
    { name: "diflucan 150 mg", type: "number", value: 0 },
    { name: "prostride cap", type: "number", value: 0 },
    { name: "finastura cap", type: "number", value: 0 },
    { name: "optaminess", type: "number", value: 0 },
    { name: "thiotacid compound 600", type: "number", value: 0 },
    { name: "urinex tab", type: "number", value: 0 },
    { name: "rowatinex cap", type: "number", value: 0 },
    { name: "kellagon cap", type: "number", value: 0 },
    { name: "zorcal 40 tab", type: "number", value: 0 },
    { name: "Zorcal 20 tab", type: "number", value: 0 },
    { name: "simecol", type: "number", value: 0 },
    { name: "cal-Mag", type: "number", value: 0 },
    { name: "trib-Gold", type: "number", value: 0 },
    { name: "Selenium ACE", type: "number", value: 0 },
    { name: "Carnivita forte", type: "number", value: 0 },
    { name: "uralyt-U", type: "number", value: 0 },
    { name: "maxilase", type: "number", value: 0 },
    { name: "acetylcysteine 600 sachets", type: "number", value: 0 },
    { name: "elica m cream", type: "number", value: 0 },
    { name: "octatron cap", type: "number", value: 0 },
    { name: "Flector 50", type: "number", value: 0 },
    { name: "prostacure cap", type: "number", value: 0 },
    { name: "albendazole syrup", type: "number", value: 0 },
    { name: "vermizole syrup", type: "number", value: 0 },
    { name: "vibramycin 100 tab", type: "number", value: 0 },
    { name: "levoxin tab", type: "number", value: 0 },
    { name: "BILICHOL tab", type: "number", value: 0 },
    { name: "buscopan tab", type: "number", value: 0 },
    { name: "Petro tab", type: "number", value: 0 },
    { name: "cipra pro 10 tab", type: "number", value: 0 },
    { name: "Omnic Ocas tab", type: "number", value: 0 },
    { name: "Genurin tab", type: "number", value: 0 },
    { name: "prostat tab", type: "number", value: 0 },
    { name: "biostrong tab", type: "number", value: 0 },
    { name: "royal care tab", type: "number", value: 0 },
    { name: "dumonrects 5 tab", type: "number", value: 0 },
    { name: "dumonrects 20 tab", type: "number", value: 0 },
    { name: "erec tab", type: "number", value: 0 },
    { name: "adolor 15 amp", type: "number", value: 0 },
    { name: "adolor 30 amp", type: "number", value: 0 },
    { name: "dalacin cream", type: "number", value: 0 },
    { name: "factu supp", type: "number", value: 0 },
    { name: "cefazone plus amp", type: "number", value: 0 },
    { name: "saline 0.9", type: "number", value: 0 },
    { name: "rowachol tap", type: "number", value: 0 },
    { name: "becozyme amp", type: "number", value: 0 },
    { name: "eposino amp", type: "number", value: 0 },
    { name: "nitazode syp", type: "number", value: 0 },
    { name: "visralgine tab", type: "number", value: 0 },
    { name: "prucasoft 2mg tab", type: "number", value: 0 },

    // Add more drugs here
  ],
};
