export default {
  drugs: [
    { name: "Ciprofar 500", type: "number", value: 0 },
    { name: "Ciprofloxacin 500", type: "number", value: 0 },
    { name: "Ciprocin 500", type: "number", value: 0 },
    { name: "ciprdiazole", type: "number", value: 0 },
    { name: "tavanic 500", type: "number", value: 0 },
    { name: "unictam 375", type: "number", value: 0 },
    { name: "tarivid 200", type: "number", value: 0 },
    { name: "septrin d.S", type: "number", value: 0 },
    { name: "augmentin 1g", type: "number", value: 0 },
    { name: "hibiotic 1g", type: "number", value: 0 },
    { name: "augmentin 600 syrup", type: "number", value: 0 },
    { name: "hibiotic 600 syrup", type: "number", value: 0 },
    { name: "clavimox 625", type: "number", value: 0 },
    { name: "averozolid tab", type: "number", value: 0 },
    { name: "linezolid tab", type: "number", value: 0 },
    { name: "linizox tab", type: "number", value: 0 },
    { name: "gynoconazol 80 supp", type: "number", value: 0 },
    { name: "viatrazo 80 supp", type: "number", value: 0 },
    { name: "abimol supp", type: "number", value: 0 },
    { name: "voltaren supp", type: "number", value: 0 },
    { name: "pyral supp", type: "number", value: 0 },
    { name: "dolphin 12.5 supp", type: "number", value: 0 },
    { name: "proximol sachets", type: "number", value: 0 },
    { name: "epimag sachets", type: "number", value: 0 },
    { name: "urivin sachets", type: "number", value: 0 },
    { name: "urosolvine sachets", type: "number", value: 0 },
    { name: "ur-Aid sachets", type: "number", value: 0 },
    { name: "septrin syrup", type: "number", value: 0 },
    { name: "septazole syrup", type: "number", value: 0 },
    { name: "suprax 30ml", type: "number", value: 0 },
    { name: "suprax 60ml", type: "number", value: 0 },
    { name: "cefixime 30ml", type: "number", value: 0 },
    { name: "cefixime 60ml", type: "number", value: 0 },

    // Add more drugs here
  ],
};
